name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/subtract_1_x2.svg
  - assets/vectors/arrow_left_4_x2.svg
  - assets/vectors/subtract_x2.svg
  - assets/vectors/arrow_left_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/objects_x2.svg
  - assets/vectors/vector_stroke_x2.svg
  - assets/vectors/objects_1_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/arrow_left_1_x2.svg
  - assets/vectors/profile_tick_x2.svg
  - assets/vectors/arrow_left_2_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/rectangle_4377_x2.svg
  - assets/vectors/rectangle_4372_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/rectangle_4376_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/rectangle_4371_x2.svg
  - assets/vectors/arrow_left_3_x2.svg
  - assets/vectors/rectangle_437_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/rectangle_4373_x2.svg
  - assets/vectors/profile_tick_1_x2.svg
  - assets/vectors/rectangle_4378_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/rectangle_4375_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_2_x2.svg

